# Generated by Django 5.2.8 on 2025-11-22 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veterinario', models.CharField(max_length=100)),
                ('data_consulta', models.DateTimeField()),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('CONFIRMADA', 'Confirmada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='AGENDADA', max_length=15)),
                ('sintomas', models.TextField(blank=True, verbose_name='Sintomas')),
                ('diagnostico', models.TextField(blank=True, verbose_name='Diagnóstico')),
                ('tratamento', models.TextField(blank=True, verbose_name='Tratamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pets.pet')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-data_consulta'],
            },
        ),
    ]
